     MOV BX,2000H      ; SI CAN BE USED INSTEAD OF BX 
     MOV AL,[BX]          ; DATA TO BE ENTERED IN 2000 MEMORY LOCATION 
     MOV CL,08H 
     MOV CH,00H 
L2:  SHR AL,1H 
     JC L1 
     INC CH 
L1:  DEC CL 
     JNZ L2 
     INC BX  
     MOV [BX],CH       ; RESULT TO BE CHECKED IN 2001 MEMORY LOCATION 
     HLT